name: golang testing
on: [push, pull_request]
jobs:
  golang_testing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: go version
      - uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: -E gofmt
      - run: go test ./..
